#!/usr/bin/python3
"""
Merge SBOM files from different sources.

Expects SBOM created from konflux buildroots and syft-generated one. It will
take the first one and extend it with data from syft.
"""

import argparse
import json


def get_params():
    """Parse command-line arguments for SBOM merging.

    :returns: Parsed command-line arguments
    :rtype: argparse.Namespace
    """
    parser = argparse.ArgumentParser()
    parser.add_argument('--sbom-spdx', required=True, help="SPDX SBOM generated by pipeline")
    parser.add_argument('--syft-sbom', required=True, help="SPDX SBOM generated by Syft")
    parser.add_argument('--sbom-merged', required=True, help="Output SPDX SBOM file")
    parser.add_argument('--source-data', help="JSON file with source data from gen_ancestors_from_src.py")
    args = parser.parse_args()
    return args


def get_generic_purl(name, version=None, url=None, checksum=None, alg=None):
    """Generate Package URL (purl) for a source package."""
    purl = f"pkg:generic/{name}"
    if version:
        purl += f"@{version}"
    if url:
        purl += f"?download_url={url}"
    if checksum:
        purl += f"&checksum={alg.lower() if alg else 'sha256'}:{checksum}"
    return purl


def attach_sources(sbom_root, source_data_file):
    """
    Add source packages from gen_ancestors_from_src.py output to SBOM.

    For each source in the source data file:
    - Creates a source package (SPDXRef-Source{idx}) with midstream url
    - Includes upstream checksum in the source package checksums
    - Generates purl using midstream URL and checksum
    - Adds CONTAINS relationship from SRPM to the source package
    - If upstream URL exists, creates an origin package (SPDXRef-Source{idx}-origin)
      with upstream properties and adds GENERATED_FROM relationship

    :param sbom_root: The root SBOM dictionary to modify, which contains (S)RPMs data
    :param source_data_file: Path to JSON file with source data from gen_ancestors_from_src.py
    """
    with open(source_data_file, encoding="utf-8") as f:
        source_data = json.load(f)
    sources = source_data.get('sources', [])

    # Add source packages to SBOM
    for idx, source in enumerate(sources):
        # Set properties based on whether midstream exists
        midstream = source.get("midstream", {})
        # Create source package
        source_pkg = {
            "SPDXID": f"SPDXRef-Source{idx}",
            "name": source["name"],
            "versionInfo": source.get("version", "unknown"),
            "packageFileName": source["filename"],
            "downloadLocation": midstream.get("url", "NOASSERTION"),
            "filesAnalyzed": False,
            "checksums": [
                # use source.checksum
                {
                    "algorithm": source["alg"],
                    "checksumValue": source["checksum"]
                }
            ],
            "externalRefs": [
                # Add purl using midstream URL and checksum
                {
                    "referenceCategory": "PACKAGE-MANAGER",
                    "referenceType": "purl",
                    "referenceLocator": get_generic_purl(
                        name=source["name"],
                        version=source.get("version"),
                        url=midstream.get("url"),
                        checksum=midstream.get("checksum"),
                        alg=midstream.get("alg")
                    )
                }
            ],
        }

        sbom_root["packages"].append(source_pkg)
        sbom_root.setdefault("relationships", []).append(
            {
                "spdxElementId": "SPDXRef-SRPM",
                "relationshipType": "CONTAINS",
                "relatedSpdxElement": f"SPDXRef-Source{idx}",
            }
        )
        # Create upstream origin package if upstream exists
        if source.get("url"):
            upstream_pkg = {
                "SPDXID": f"SPDXRef-Source{idx}-origin",
                "name": source["name"],
                "versionInfo": source.get("version", "unknown"),
                "downloadLocation": source.get("url"),
                "packageFileName": source["filename"],
                "filesAnalyzed": False,
            }

            # Add upstream checksum if available
            if source.get("checksum") and source.get("alg"):
                upstream_pkg["checksums"] = [{
                    "algorithm": source["alg"],
                    "checksumValue": source["checksum"]
                }]

            # Add purl as external reference
            upstream_pkg["externalRefs"] = [{
                "referenceCategory": "PACKAGE-MANAGER",
                "referenceType": "purl",
                "referenceLocator": get_generic_purl(
                    name=source["name"],
                    version=source.get("version"),
                    url=source.get("url"),
                    checksum=source.get("checksum"),
                    alg=source.get("alg")
                )
            }]

            sbom_root['packages'].append(upstream_pkg)

            # Add relationship: midstream GENERATED_FROM upstream
            sbom_root['relationships'].append({
                "spdxElementId": f"SPDXRef-Source{idx}",
                "relationshipType": "GENERATED_FROM",
                "relatedSpdxElement": f"SPDXRef-Source{idx}-origin",
            })


def merge_sboms(root_sbom, syft_sbom, output_sbom, source_data_file=None):
    """Merge SPDX SBOMs from different sources into a single output file.

    :param root_sbom: Path to the root SBOM file (from SRPM)
    :type root_sbom: str
    :param syft_sbom: Path to the Syft-generated SBOM file
    :type syft_sbom: str
    :param output_sbom: Path to the output merged SBOM file
    :type output_sbom: str
    :param source_data_file: Optional path to source data JSON from gen_ancestors_from_src.py
    :type source_data_file: str or None
    """
    with open(root_sbom, encoding="utf-8") as f:
        sbom_root = json.load(f)
    with open(syft_sbom, encoding="utf-8") as f:
        sbom_syft = json.load(f)

    # https://github.com/RedHatProductSecurity/security-data-guidelines/blob/main/sbom/examples/rpm/build/from-koji.py
    syft_pkgs = sbom_syft.get('packages', [])
    for pkg in syft_pkgs:
        if "externalRefs" not in pkg:
            continue

    sbom_root['packages'].extend(syft_pkgs)
    sbom_root['files'].extend(sbom_syft.get("files", []))
    syft_rels = sbom_syft.get("relationships", [])

    # Adjust top-level relationship to document, to link it into Source0
    # of our sources.
    for relationship in syft_rels:
        if (
            relationship["spdxElementId"] == "SPDXRef-DOCUMENT"
            and relationship["relationshipType"] == "DESCRIBES"
        ):
            relationship["spdxElementId"] = "SPDXRef-Source0"  # pick first one
            relationship["relationshipType"] = "CONTAINS"
    sbom_root['relationships'].extend(syft_rels)

    # Add source data if provided
    if source_data_file:
        attach_sources(sbom_root, source_data_file)

    with open(output_sbom, 'wt', encoding="utf-8") as f:
        json.dump(sbom_root, f)


def _main():
    args = get_params()
    merge_sboms(args.sbom_spdx, args.syft_sbom, args.sbom_merged, args.source_data)
    if args.source_data:
        print(f"{args.sbom_spdx}, {args.syft_sbom}, and {args.source_data} merged to {args.sbom_merged}")
    else:
        print(f"{args.sbom_spdx} and {args.syft_sbom} merged to {args.sbom_merged}")


if __name__ == "__main__":
    _main()
