#!/usr/bin/python3
"""
Merge SBOM files from different sources.

Expects SBOM created from konflux buildroots and syft-generated one. It will
take the first one and extend it with data from syft.
"""

import argparse
import datetime
import glob
import hashlib
import json
import logging
import os

import koji

from common_utils import calc_checksum
from sbom_utils import to_spdx_license, get_generic_purl, get_rpm_purl


SBOM_CREATOR = "Tool: Konflux"
SBOM_CREATED_TIME = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def get_params():
    """Parse command-line arguments for SBOM merging.

    :returns: Parsed command-line arguments
    :rtype: argparse.Namespace
    """
    parser = argparse.ArgumentParser()
    parser.add_argument('--rpm-dir', default='.',
                        help="Directory containing RPM files, e.g., STAGING_DIR. (default: current directory)")
    parser.add_argument('--syft-sbom', required=True, help="SPDX SBOM generated by Syft")
    parser.add_argument('--sbom-merged', required=True, help="Output SPDX SBOM file")
    parser.add_argument('--source-data', help="JSON file with source data from gen_ancestors_from_src.py")
    parser.add_argument(
        '--buildroot-arch-list',
        help="JSON file with buildroot arch list from gather_rpms (buildroot_rpms.json)"
    )
    parser.add_argument(
        '--syft-sbom-dir',
        default='.',
        help="Directory containing syft-generated SBOM files for SRPM and binary RPMs (default: current directory)"
    )
    args = parser.parse_args()
    return args


def create_base_sbom(rpm_dir):
    """Generate base SBOM from RPM directory.

    Scans directory for SRPM and binary RPMs, creates SPDX 2.3 document
    with packages and relationships.

    :param rpm_dir: Directory containing RPM files
    :type rpm_dir: str
    :returns: SBOM dictionary
    :rtype: dict
    """
    srpm = None
    rpms = []  # List of binary RPM filenames

    # Scan directory for RPMs
    for filename in sorted(os.listdir(rpm_dir)):
        if filename.endswith('.src.rpm'):
            if not srpm:
                srpm = filename
        elif filename.endswith('.rpm'):
            rpms.append(filename)

    if not srpm:
        raise FileNotFoundError(f"No SRPM found in {rpm_dir}")

    nvr = srpm[:-8]  # Remove .src.rpm extension

    # Initialize SBOM structure
    sbom = {
        "spdxVersion": "SPDX-2.3",
        "dataLicense": "CC0-1.0",
        "SPDXID": "SPDXRef-DOCUMENT",
        "creationInfo": {
            "created": SBOM_CREATED_TIME,
            "creators": [
                SBOM_CREATOR
            ],
        },
        "name": nvr,
        "documentNamespace": f"https://www.redhat.com/{nvr}.spdx.json",
        "packages": [],
        "files": [],
        "relationships": [
            {
                "spdxElementId": "SPDXRef-DOCUMENT",
                "relationshipType": "DESCRIBES",
                "relatedSpdxElement": "SPDXRef-SRPM"
            },
        ],
    }

    # Process SRPM and all binary RPMs
    rpm_spdxids = []
    for rpm in [srpm] + rpms:
        path = os.path.join(rpm_dir, rpm)

        rpminfo = koji.get_header_fields(
            path,
            [
                "name",
                "version",
                "release",
                "epoch",
                "arch",
                "description",
                "license",
                "sigmd5",
                "sha256header",
                "sourcepackage",
                "sourcerpm",
            ],
        )

        # check by arch in filename (arch in header is actually the buildarch)
        if rpminfo['sourcepackage']:
            spdxid = "SPDXRef-SRPM"
            rpminfo['arch'] = "src"
        else:
            spdxid = f"SPDXRef-{rpminfo['arch']}-{rpminfo['name']}"

        rpm_spdxids.append(spdxid)

        # Get license and convert to SPDX format
        spdx_license = to_spdx_license(rpminfo['license'])

        sbom['packages'].append({
            "SPDXID": spdxid,
            "name": rpminfo['name'],
            "versionInfo": f"{rpminfo['version']}-{rpminfo['release']}",
            "supplier": "Organization: Red Hat",
            "downloadLocation": "NOASSERTION",
            "packageFileName": rpm,
            "licenseDeclared": spdx_license,
            "externalRefs": [
                {
                    "referenceCategory": "PACKAGE-MANAGER",
                    "referenceType": "purl",
                    "referenceLocator": get_rpm_purl(
                        name=rpminfo['name'],
                        version=rpminfo['version'],
                        release=rpminfo['release'],
                        arch=rpminfo['arch'],
                        epoch=rpminfo.get('epoch')
                    ),
                }
            ],
            "checksums": [
                {
                    "algorithm": "SHA256",
                    "checksumValue": calc_checksum(path, algorithm="sha256"),
                }
            ],
        })

        # All binary RPMs are generated from SRPM
        if rpminfo['arch'] != "src":
            if rpminfo.get('sourcerpm') and rpminfo['sourcerpm'] != srpm:
                raise ValueError(
                    f"[CRITICAL] Binary RPM {rpm} has sourcerpm header {rpminfo['sourcerpm']}"
                    f" that does not match expected SRPM {srpm}",
                )
            sbom['relationships'].append({
                "spdxElementId": spdxid,
                "relationshipType": "GENERATED_FROM",
                "relatedSpdxElement": "SPDXRef-SRPM",
            })

    # Set documentDescribes to list all RPMs
    sbom['documentDescribes'] = rpm_spdxids

    return sbom


def attach_sources(sbom_root, source_data_file):
    """
    Add source packages from gen_ancestors_from_src.py output to SBOM.

    For each source in the source data file:
    - Creates a source package (SPDXRef-Source{idx}) with midstream url
    - Includes upstream checksum in the source package checksums
    - Generates purl using midstream URL and checksum
    - Adds CONTAINS relationship from SRPM to the source package
    - If upstream URL exists, creates an origin package (SPDXRef-Source{idx}-origin)
      with upstream properties and adds GENERATED_FROM relationship

    :param sbom_root: The root SBOM dictionary to modify, which contains (S)RPMs data
    :param source_data_file: Path to JSON file with source data from gen_ancestors_from_src.py
    """
    with open(source_data_file, encoding="utf-8") as f:
        source_data = json.load(f)
    sources = source_data.get('sources', [])

    # Add source packages to SBOM
    for idx, source in enumerate(sources):
        # Set properties based on whether midstream exists
        midstream = source.get("midstream", {})
        # Create source package
        source_pkg = {
            "SPDXID": f"SPDXRef-Source{idx}",
            "name": source["name"],
            "versionInfo": source.get("version", "unknown"),
            "packageFileName": source["filename"],
            "downloadLocation": midstream.get("url", "NOASSERTION"),
            "filesAnalyzed": False,
            "checksums": [
                # use source.checksum
                {
                    "algorithm": source["alg"],
                    "checksumValue": source["checksum"]
                }
            ],
            "externalRefs": [
                # Add purl using midstream URL and checksum
                {
                    "referenceCategory": "PACKAGE-MANAGER",
                    "referenceType": "purl",
                    "referenceLocator": get_generic_purl(
                        name=source["name"],
                        version=source.get("version"),
                        url=midstream.get("url"),
                        checksum=midstream.get("checksum"),
                        alg=midstream.get("alg")
                    )
                }
            ],
        }

        sbom_root["packages"].append(source_pkg)
        sbom_root.setdefault("relationships", []).append(
            {
                "spdxElementId": "SPDXRef-SRPM",
                "relationshipType": "CONTAINS",
                "relatedSpdxElement": f"SPDXRef-Source{idx}",
            }
        )
        # Create upstream origin package if upstream exists
        if source.get("url"):
            upstream_pkg = {
                "SPDXID": f"SPDXRef-Source{idx}-origin",
                "name": source["name"],
                "versionInfo": source.get("version", "unknown"),
                "downloadLocation": source.get("url"),
                "packageFileName": source["filename"],
                "filesAnalyzed": False,
            }

            # Add upstream checksum if available
            if source.get("checksum") and source.get("alg"):
                upstream_pkg["checksums"] = [{
                    "algorithm": source["alg"],
                    "checksumValue": source["checksum"]
                }]

            # Add purl as external reference
            upstream_pkg["externalRefs"] = [{
                "referenceCategory": "PACKAGE-MANAGER",
                "referenceType": "purl",
                "referenceLocator": get_generic_purl(
                    name=source["name"],
                    version=source.get("version"),
                    url=source.get("url"),
                    checksum=source.get("checksum"),
                    alg=source.get("alg")
                )
            }]

            sbom_root['packages'].append(upstream_pkg)

            # Add relationship: midstream GENERATED_FROM upstream
            sbom_root['relationships'].append({
                "spdxElementId": f"SPDXRef-Source{idx}",
                "relationshipType": "GENERATED_FROM",
                "relatedSpdxElement": f"SPDXRef-Source{idx}-origin",
            })


def _find_rpm_packages(sbom_root):
    """
    Build a dictionary mapping NVRA to RPM package items.

    :param sbom_root: The root SBOM dictionary
    :type sbom_root: dict
    :returns: Dictionary with NVRA as key and package dict as value
    :rtype: dict
    """
    rpm_packages = {}

    for pkg in sbom_root.get("packages", []):
        pkg_filename = pkg.get("packageFileName", "")

        # Only process .rpm files (skip .src.rpm)
        if pkg_filename.endswith(".rpm") and not pkg_filename.endswith(".src.rpm"):
            # Remove .rpm extension to get NVRA
            nvra = pkg_filename[:-4]
            rpm_packages[nvra] = pkg

    return rpm_packages


def _rename_doc_root_id(rpm_sbom, nvra):
    """
    Generate new SPDXID for the DocumentRoot element to avoid collisions.

    Finds the element that SPDXRef-DOCUMENT describes and returns a new unique ID.

    :param rpm_sbom: SBOM dictionary from RPM scanning
    :type rpm_sbom: dict
    :param nvra: RPM NVRA string for unique naming
    :type nvra: str
    :returns: Tuple of (old_root_id, new_root_id) or (None, None) if not found
    :rtype: tuple
    """
    # Find what SPDXRef-DOCUMENT describes
    old_root_id = None
    for rel in rpm_sbom.get("relationships", []):
        if (rel.get("spdxElementId") == "SPDXRef-DOCUMENT" and
                rel.get("relationshipType") == "DESCRIBES"):
            old_root_id = rel.get("relatedSpdxElement")
            break

    if not old_root_id:
        logging.warning("No DOCUMENT DESCRIBES relationship found in RPM SBOM for %s", nvra)
        return None, None

    # Create new root ID
    new_root_id = f"SPDXRef-Directory-Root-{nvra}"

    return old_root_id, new_root_id


def attach_syft_sboms(sbom_root, syft_sbom_dir):
    """
    Merge syft-generated SBOMs from SRPM and binary RPMs into the root SBOM.

    For each RPM SBOM file in the directory:
    - Match it to an SRPM or binary RPM package by NVRA
    - Rename the document root to avoid ID collisions
    - Merge all packages, files, and relationships
    - Create CONTAINS relationship from RPM to document root

    :param sbom_root: The root SBOM dictionary to modify
    :type sbom_root: dict
    :param syft_sbom_dir: Directory containing syft-generated SBOM JSON files for SRPM and binary RPMs
    :type syft_sbom_dir: str
    """

    # Build mapping of NVRA to RPM packages
    rpm_packages = _find_rpm_packages(sbom_root)

    if not syft_sbom_dir:
        raise ValueError("syft_sbom_dir parameter is required for attaching RPM SBOMs")

    # Find all .sbom.json files in the directory
    sbom_pattern = os.path.join(syft_sbom_dir, "*.sbom.json")
    sbom_files = glob.glob(sbom_pattern)

    if not sbom_files:
        logging.info("No .sbom.json files found in %s", syft_sbom_dir)
        return

    for sbom_file in sbom_files:
        # Extract NVRA from filename
        # Expected format: {nvra}.sbom.json
        base_name = os.path.basename(sbom_file)
        if not base_name.endswith(".sbom.json"):
            continue

        nvra = base_name[:-len(".sbom.json")]

        # Find matching RPM package
        rpm_pkg = rpm_packages.get(nvra)
        if not rpm_pkg:
            logging.warning("No matching RPM package found for %s", nvra)
            continue

        # Load RPM SBOM
        try:
            with open(sbom_file, encoding="utf-8") as f:
                rpm_sbom = json.load(f)
        except (json.JSONDecodeError, OSError) as e:
            logging.error("Failed to load RPM SBOM %s: %s", sbom_file, e)
            continue

        # Get old and new document root IDs
        old_root_id, new_root_id = _rename_doc_root_id(rpm_sbom, nvra)
        if not old_root_id or not new_root_id:
            logging.warning("Skipping RPM SBOM %s: could not find document root", nvra)
            continue

        # Replace old root ID with new root ID in packages
        for pkg in rpm_sbom.get("packages", []):
            if pkg.get("SPDXID") == old_root_id:
                pkg["SPDXID"] = new_root_id

        # Replace old root ID with new root ID in files
        for file_item in rpm_sbom.get("files", []):
            if file_item.get("SPDXID") == old_root_id:
                file_item["SPDXID"] = new_root_id

        # Replace old root ID with new root ID in relationships
        for rel in rpm_sbom.get("relationships", []):
            if rel.get("spdxElementId") == old_root_id:
                rel["spdxElementId"] = new_root_id
            if rel.get("relatedSpdxElement") == old_root_id:
                rel["relatedSpdxElement"] = new_root_id

        # Merge packages, files, and relationships into root SBOM
        sbom_root.setdefault("packages", []).extend(rpm_sbom.get("packages", []))
        sbom_root.setdefault("files", []).extend(rpm_sbom.get("files", []))
        sbom_root.setdefault("relationships", []).extend(rpm_sbom.get("relationships", []))

        # Add CONTAINS relationship from binary RPM to document root
        sbom_root["relationships"].append({
            "spdxElementId": rpm_pkg["SPDXID"],
            "relationshipType": "CONTAINS",
            "relatedSpdxElement": new_root_id
        })

        logging.info("Merged RPM SBOM for %s", nvra)


def attach_buildroot_packages(sbom_root, broot_arch_list_file, srpm_name):  # pylint: disable=R0914
    """
    Add buildroot packages from buildroot arch list to SBOM.

    Reads the buildroot arch list JSON file (output from gather_rpms.py),
    which maps architectures to their RPM lists and lockfile paths.

    For each architecture:
    - Read the lockfile path from the arch list
    - Parse the buildroot.rpms list from the lockfile
    - Create a virtual buildroot package per architecture
    - Create SPDX packages for each buildroot RPM
    - Add CONTAINS relationships from virtual package to buildroot RPMs
    - Add BUILD_TOOL_OF relationships from virtual package to binary RPMs

    :param sbom_root: The root SBOM dictionary to modify
    :type sbom_root: dict
    :param broot_arch_list_file: Path to buildroot arch list JSON file (buildroot_rpms.json)
    :type broot_arch_list_file: str
    :param srpm_name: Name of the SRPM being built (for virtual package naming)
    :type srpm_name: str
    """
    if not broot_arch_list_file:
        return

    # Read buildroot arch list JSON
    with open(broot_arch_list_file, encoding="utf-8") as f:
        buildroot_arch_list = json.load(f)

    # Iterate through each architecture in the buildroot arch list
    for arch, arch_data in buildroot_arch_list.items():
        lockfile_path = arch_data.get("lockfile")
        if not lockfile_path:
            logging.warning("No lockfile path for arch %s, skipping", arch)
            continue

        # Read the lockfile
        try:
            with open(lockfile_path, encoding="utf-8") as f:
                lockfile_data = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            logging.error("Failed to read lockfile %s for arch %s: %s", lockfile_path, arch, e)
            continue

        # Extract target architecture from config (should match the arch key)
        target_arch = lockfile_data.get("config", {}).get("target_arch", arch)
        if target_arch != arch:
            logging.warning(
                "Target arch mismatch: arch key=%s, lockfile target_arch=%s, using %s",
                arch, target_arch, arch
            )
            target_arch = arch

        # Create virtual buildroot package for this architecture
        virtual_spdx_id = f"SPDXRef-Buildroot-{srpm_name}-{target_arch}"
        sbom_root["packages"].append({
            "SPDXID": virtual_spdx_id,
            "name": f"{srpm_name}-buildroot-{target_arch}",
            # Calculate a unique version identifier (hash of lockfile path)
            "versionInfo": hashlib.sha256(lockfile_path.encode()).hexdigest()[:8],
            "downloadLocation": "NOASSERTION",
            "filesAnalyzed": False,
        })

        # Get buildroot RPMs
        buildroot_rpms = lockfile_data.get("buildroot", {}).get("rpms", [])

        for rpm in buildroot_rpms:
            # Create unique SPDXID using rpm name and arch
            spdx_id = f"SPDXRef-Buildroot-Package-{rpm['name']}-{target_arch}"

            # Build version string (version-release with optional epoch prefix)
            version = f"{rpm['version']}-{rpm['release']}"
            if rpm.get('epoch'):
                version = f"{rpm['epoch']}:{version}"

            # Create buildroot package dictionary
            pkg_dict = {
                "SPDXID": spdx_id,
                "name": rpm["name"],
                "versionInfo": version,
                "downloadLocation": rpm.get("url", "NOASSERTION"),
                "licenseDeclared": to_spdx_license(rpm.get("license")),
                "filesAnalyzed": False,
                "supplier": "Organization: Red Hat",
                "annotations": []
            }

            # Add checksum if sigmd5 as an annotation
            sigmd5 = rpm.get("sigmd5")
            if sigmd5:
                pkg_dict["annotations"].append({
                    "annotationType": "OTHER",
                    "annotator": SBOM_CREATOR,
                    "annotationDate": SBOM_CREATED_TIME,
                    "comment": f"sigmd5: {sigmd5}",
                })
            # Add sha256header if sha256header as an annotation (mock doesn't provide it yet)
            sha256header = rpm.get("sha256header")
            if sha256header:
                pkg_dict["annotations"].append({
                    "annotationType": "OTHER",
                    "annotator": SBOM_CREATOR,
                    "annotationDate": SBOM_CREATED_TIME,
                    "comment": f"sha256header: {sha256header}",
                })

            # Add RPM purl as external reference
            pkg_dict["externalRefs"] = [{
                "referenceCategory": "PACKAGE-MANAGER",
                "referenceType": "purl",
                "referenceLocator": get_rpm_purl(
                    name=rpm["name"],
                    version=rpm["version"],
                    release=rpm["release"],
                    arch=rpm["arch"],
                    epoch=rpm.get("epoch")
                )
            }]

            sbom_root["packages"].append(pkg_dict)

            # Add CONTAINS relationship from virtual package to buildroot RPM
            sbom_root.setdefault("relationships", []).append({
                "spdxElementId": virtual_spdx_id,
                "relationshipType": "CONTAINS",
                "relatedSpdxElement": spdx_id
            })

        # Find binary RPMs built for this architecture
        # and add BUILD_TOOL_OF relationships from virtual package
        for pkg in sbom_root["packages"]:
            # Skip packages without external refs or buildroot-related packages
            if not pkg.get("externalRefs"):
                continue

            pkg_id = pkg.get("SPDXID", "")
            if pkg_id.startswith("SPDXRef-Buildroot-"):
                continue

            # Check if this is a binary RPM for the target architecture
            pkg_purl = pkg["externalRefs"][0].get("referenceLocator", "")
            if f"arch={target_arch}" in pkg_purl and "pkg:rpm/" in pkg_purl:
                # Add BUILD_TOOL_OF relationship from virtual buildroot package
                sbom_root.setdefault("relationships", []).append({
                    "spdxElementId": virtual_spdx_id,
                    "relationshipType": "BUILD_TOOL_OF",
                    "relatedSpdxElement": pkg["SPDXID"]
                })


def merge_sboms(
        root_sbom, syft_sbom, output_sbom, *,
        source_data_file=None, broot_arch_list_file=None, syft_sbom_dir=None):
    """Merge SPDX SBOMs from different sources into a single output file.

    :param root_sbom: Root SBOM dictionary (from SRPM and binary RPMs)
    :type root_sbom: dict
    :param syft_sbom: Path to the Syft-generated SBOM file
    :type syft_sbom: str
    :param output_sbom: Path to the output merged SBOM file
    :type output_sbom: str
    :param source_data_file: Optional path to source data JSON from gen_ancestors_from_src.py
    :type source_data_file: str or None
    :param broot_arch_list_file: Optional path to buildroot arch list JSON file (buildroot_rpms.json)
    :type broot_arch_list_file: str or None
    :param syft_sbom_dir: Optional directory containing syft-scanned SBOM JSON files for the SRPM and Binary RPMs
    :type syft_sbom_dir: str or None
    """
    with open(syft_sbom, encoding="utf-8") as f:
        sbom_syft = json.load(f)

    # https://github.com/RedHatProductSecurity/security-data-guidelines/blob/main/sbom/examples/rpm/build/from-koji.py
    syft_pkgs = sbom_syft.get('packages', [])
    for pkg in syft_pkgs:
        if "externalRefs" not in pkg:
            continue

    root_sbom['packages'].extend(syft_pkgs)
    root_sbom['files'].extend(sbom_syft.get("files", []))
    syft_rels = sbom_syft.get("relationships", [])

    # Adjust top-level relationship to document, to link it into Source0
    # of our sources.
    for relationship in syft_rels:
        if (
            relationship["spdxElementId"] == "SPDXRef-DOCUMENT"
            and relationship["relationshipType"] == "DESCRIBES"
        ):
            relationship["spdxElementId"] = "SPDXRef-SRPM"
            relationship["relationshipType"] = "CONTAINS"
            break
    root_sbom['relationships'].extend(syft_rels)

    # Add source data if provided
    if source_data_file:
        attach_sources(root_sbom, source_data_file)

    # Add buildroot packages if buildroot arch list provided
    if broot_arch_list_file:
        # Extract SRPM name from the root SBOM document name
        # Format is typically: "package-name-version-release"
        # We want just the package name
        srpm_name = root_sbom.get("name", "unknown").rsplit("-", 2)[0]
        attach_buildroot_packages(root_sbom, broot_arch_list_file, srpm_name)

    # Add RPM SBOM packages if directory provided
    if syft_sbom_dir:
        attach_syft_sboms(root_sbom, syft_sbom_dir)

    with open(output_sbom, 'wt', encoding="utf-8") as f:
        json.dump(root_sbom, f)


def _main():
    args = get_params()

    # Generate base SBOM from RPM directory
    root_sbom = create_base_sbom(args.rpm_dir)

    merge_sboms(
        root_sbom,
        args.syft_sbom,
        args.sbom_merged,
        source_data_file=args.source_data,
        broot_arch_list_file=args.buildroot_arch_list,
        syft_sbom_dir=args.syft_sbom_dir
    )

    # Build output message
    print(f"Generated SBOM from RPMs in: {args.rpm_dir}")
    print(f"Merged with Syft SBOM: {args.syft_sbom}")
    if args.source_data:
        print(f"  - Added source data from: {args.source_data}")
    if args.buildroot_arch_list:
        print(f"  - Added buildroot packages from: {args.buildroot_arch_list}")
    if args.syft_sbom_dir:
        print(f"  - Merged RPM SBOMs from: {args.syft_sbom_dir}")
    print(f"Output written to: {args.sbom_merged}")


if __name__ == "__main__":
    _main()
