---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: test-pipeline
spec:
  tasks:
    - name: test hello
      taskSpec:
        steps:
          - name: echo
            image: alpine
            script: |
              echo "Hello World!"

---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/konflux-ci/rpmbuild-pipeline-environment-container?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: oci-images
    appstudio.openshift.io/component: environment
    pipelines.appstudio.openshift.io/type: build
  name: environment-on-pull-request
  namespace: rpm-build-pipeline-tenant
spec:
  pipelineSpec:
    tasks:
      - name: run-different-pipeline
        pipelineRef:
          name: test-pipeline
