---
name: pre-commit

on:
  push:
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: quay.io/redhat-artifact-storage/pre-commit-image@sha256:a2c720a39bd9f0fe3301c79a1aa16ebc2f3705a18663e7812e8eac94d8fd62a2

    steps:
      - name: Repository checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
        env:
          SKIP: shellcheck,pylint
        with:
          extra_args: --from-ref origin/main --to-ref HEAD
