---
name: pre-commit

on:
  push:
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: quay.io/redhat-artifact-storage/pre-commit-image@sha256:cd6c77c93373645ba5c2dc3277d1117610ab6733690031830f91163bf76ad66c

    steps:
      - name: Repository checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
        env:
          SKIP: shellcheck,pylint
        with:
          extra_args: --from-ref origin/main --to-ref HEAD
